import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbar,
    MatNavList,
    MatIcon,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatCardModule,
    MatPaginatorModule,
    MatTableModule,
    MatFormFieldModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTabsModule,
    MatInputModule,
    MatDialogModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatSliderModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatAutocompleteModule,
    MatExpansionModule, MatProgressBarModule, MatRadioModule
} from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';


@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatIconModule,
        MatCardModule,
        MatPaginatorModule,
        MatTableModule,
        MatFormFieldModule,
        MatSelectModule,
        MatSortModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTabsModule,
        MatInputModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatTooltipModule,
        MatSliderModule,
        MatChipsModule,
        MatSlideToggleModule,
        MatProgressBarModule,
        MatExpansionModule,
        MatRadioModule,
        MatGridListModule,
        MatAutocompleteModule,
        BrowserAnimationsModule
    ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatIconModule,
        MatCardModule,
        MatPaginatorModule,
        MatTableModule,
        MatFormFieldModule,
        MatProgressSpinnerModule,
        MatSelectModule,
        MatSortModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTabsModule,
        MatInputModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatTooltipModule,
        MatSliderModule,
        MatChipsModule,
        MatSlideToggleModule,
        MatProgressBarModule,
        MatExpansionModule,
        MatRadioModule,
        MatGridListModule,
        MatAutocompleteModule,
        BrowserAnimationsModule
    ],
    declarations: []
})
export class MaterialModule {
}
